# python main.py -na --filename '人あり　コンクリタイル_yolov3'
# python main.py -na --filename '人あり　ラジオ体操_yolov3'
# python main.py -na --filename '人あり　香取一周_yolov3'
# python main.py -na --filename '人あり　土_yolov3'
# python main.py -na --filename '人あり　部品置き場_yolov3'
# python main.py -na --filename '人あり　舗装路（陰影あり）_yolov3'
# python main.py -na --filename '人あり　未舗装路（カニ歩き）_yolov3'
# python main.py -na --filename '人あり　未舗装路（ステップ移動）_yolov3'
# python main.py -na --filename '人あり　未舗装路（陰影あり２）_yolov3'
# python main.py -na --filename '人あり　未舗装路（無帽）_yolov3'
# python main.py -na --filename '人あり　未舗装路２_yolov3'
python main.py -na --filename '人あり　コンクリタイル_yolov3'
python main.py -na --filename '人あり　ラジオ体操_yolov3'
python main.py -na --filename '人あり　香取一周_yolov3'
python main.py -na --filename '人あり　土_yolov3'
python main.py -na --filename '人あり　部品置き場_yolov3'
python main.py -na --filename '人あり　舗装路（陰影あり）_yolov3'
python main.py -na --filename '人あり　未舗装路（カニ歩き）_yolov3'
python main.py -na --filename '人あり　未舗装路（ステップ移動）_yolov3'
python main.py -na --filename '人あり　未舗装路（陰影あり２）_yolov3'
python main.py -na --filename '人あり　未舗装路（無帽）_yolov3'
python main.py -na --filename '人あり　未舗装路２_yolov3'
# python main.py -na --filename '人あり　コンクリタイル_ssd'
# python main.py -na --filename '人あり　ラジオ体操_ssd'
# python main.py -na --filename '人あり　香取一周_ssd'
# python main.py -na --filename '人あり　土_ssd'
# python main.py -na --filename '人あり　部品置き場_ssd'
# python main.py -na --filename '人あり　舗装路（陰影あり）_ssd'
# python main.py -na --filename '人あり　未舗装路（カニ歩き）_ssd'
# python main.py -na --filename '人あり　未舗装路（ステップ移動）_ssd'
# python main.py -na --filename '人あり　未舗装路（陰影あり２）_ssd'
# python main.py -na --filename '人あり　未舗装路（無帽）_ssd'
# python main.py -na --filename '人あり　未舗装路２_ssd'
